name: Zizz
description: A Flutter project for spajam team hiyokogumi
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: 1.1.0
  chat_bubbles: ^1.5.0
  cloud_firestore: ^4.9.1
  google_maps_flutter: ^2.5.0
  ulid: ^2.0.0
  shared_preferences: ^2.2.1
  firebase_auth: ^4.9.0
  timeago: ^3.5.0
  camera: ^0.10.5+4
  geolocator: ^10.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_webrtc: ^0.9.43
  sdp_transform: ^0.3.2
  agora_rtc_engine: 6.2.2
  permission_handler: ^11.0.0
  flutter_native_splash: ^2.3.2

# you need to run `flutter pub run flutter_native_splash:create` to generate splash
flutter_native_splash:
  color: '#FFD72E'
  image: 'assets/images/splash4x.png'
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# you need to run `flutter pub run flutter_launcher_icons:main` to generate icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
