// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy_J0feCyX1l3fwNtOQlrF5kOFoXdI64o',
    appId: '1:557819657554:web:aa0a70b593773ebcb50e8b',
    messagingSenderId: '557819657554',
    projectId: 'spajam-2023-hiyokogumi',
    authDomain: 'spajam-2023-hiyokogumi.firebaseapp.com',
    storageBucket: 'spajam-2023-hiyokogumi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiO6jsqoPlBwF6ABZa0dSjb5uu_yl5TkM',
    appId: '1:557819657554:android:7f92bbc9060537cbb50e8b',
    messagingSenderId: '557819657554',
    projectId: 'spajam-2023-hiyokogumi',
    storageBucket: 'spajam-2023-hiyokogumi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQC8KI8rOdSH-Gq_HlXU0AKBHJMO01Auw',
    appId: '1:557819657554:ios:5b3860206f4846a2b50e8b',
    messagingSenderId: '557819657554',
    projectId: 'spajam-2023-hiyokogumi',
    storageBucket: 'spajam-2023-hiyokogumi.appspot.com',
    iosBundleId: 'com.example.spajam2023Hiyokogumi',
  );
}
